setopt EXTENDED_GLOB


alias vi=nvim
alias vim=nvim
alias svim="sudo -E nvim"

source ~/.zprezto/init.zsh

# prompt cloud →

export CONFIG_FOLDER=$HOME/config-management/configs
export EDITOR="nvim"
export VISUAL="nvim"

# For BlinDate
export POSTGRES_USER=postgres
export POSTGRES_PASSWORD=postgres
export POSTGRES_DB=blindate

unalias sl

fortune -s | cowsay
