setopt EXTENDED_GLOB


alias vi=nvim
alias vim=nvim
alias svim="sudo -E nvim"

source ~/.zprezto/init.zsh

# prompt cloud →

export CONFIG_FOLDER=$HOME/config-management/configs
export EDITOR="nvim"
export VISUAL="nvim"

# For BlinDate
export POSTGRES_USER=postgres
export POSTGRES_PASSWORD=postgres
export POSTGRES_DB=blindate
export POSTGRES_TEST_DB=blindate_test
export LOCAL_PORT=8000
export PATH=/home/shivnshu/google-cloud-sdk/bin:$PATH

unalias sl

fortune -s | cowsay
