#!/bin/bash

# Using Nvidia for X server
#xrandr --setprovideroutputsource modesetting NVIDIA-0
#xrandr --auto
#xrandr --dpi 96 # fix high resolution

# Load resources
xrdb -merge .Xresources

#eh --bg-scale /home/shivnshu/Pictures/wallpaper.jpg

export TERMINAL=termite
#export LC_ALL=C
#export LOCALE_ARCHIVE="$(readlink ~/.nix-profile/lib/locale)/locale-archive"

# fix java issues
#wmname LG3D

# Fire up apps
#compton -f &
#guake &
#(sleep 30; slack) &
#thunderbird&
#xmonad&
#taffybar&
#nm-applet&
#blueman-applet&
#urxvtd --quiet --opendisplay --fork

#sudo -b nohup nvidia-docker-plugin > /tmp/nvidia-docker.log
